apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-db-pvc
  namespace: laravel-deploy-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-db
  namespace: laravel-deploy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      serviceAccountName: peter-admin
      containers:
        - name: db
          image: thaigiaduc/laravel-first-app-db
          ports:
            - containerPort: 3307
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: HR
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: laravel-db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: laravel-deploy-app
spec:
  selector:
    app: db
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306