# role-binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-app-role-binding
subjects:
- kind: ServiceAccount
  name: peter-admin
roleRef:
  kind: Role
  name: laravel-deploy-app-role
  apiGroup: rbac.authorization.k8s.io
